# Workflow name
name: C/C++ CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Step 1: Checks-out your repository AND ITS SUBMODULES.
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # This is the crucial line that was added.

    # Step 2: Install necessary build tools (g++, make)
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 3: Build the application using the Makefile
    # (Building the main target isn't strictly necessary to run tests, but it's good practice)
    - name: Build application
      run: make

    # Step 4: Run the automated tests via the Makefile
    - name: Run tests
      run: make test

